#配置服务端口
server:
  port: 8006

#配置文件段类型
spring: 
  profiles: 
    dev
  application: 
    name: random
  datasource: #数据源配置 
     type:  com.alibaba.druid.pool.DruidDataSource
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.1.181:3306/yitong?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
     username: root
     password: 1234
     # 下面为连接池的补充设置，应用到上面所有数据源中
     # 初始化大小，最小，最大
     initialSize: 1
     minIdle: 3
     maxActive: 20
     # 配置获取连接等待超时的时间
     maxWait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 60000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 30000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     # 打开PSCache，并且指定每个连接上PSCache的大小
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 20
     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
     filters: stat,wall,slf4j
     # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
     # 合并多个DruidDataSource的监控数据
     useGlobalDataSourceStat: true
  redis:
    host: 127.0.0.1
    port: 6379
    port: 6388
    password: admin
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0

  boot: 
    admin:
      client:
        url:
          - http://localhost:8788
  
  #sleuth配置信息        
  zipkin:
    base-url: http://zipkin.com:8601 # 所有的数据提交到此服务之中
  sleuth:
    sampler: 
     probability: 1.0 # 定义抽样比率，默认为0.1        
          
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS
        
          
                
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    #mybatis配置文件所在路径
  type-aliases-package: com.jiurun.random.base.entity           #所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

#服务注册中心配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://192.168.1.212:7003/eureka/
  instance: 
    instance-id: random-8001
    prefer-ip-address: true #访问路径可以显示IP地址  

#系统日志配置    
#logging:
#  level:
#    com.jiurun.random.base.dao.*: DEBUG 
    
shiro:
  session:
    #shiro session前缀
    session-prefix : "shiro-redis-session"
    #shiro session 在redis过期时间是(分钟)
    session-time : 1800
  cache:
    #shiro缓存前缀
    cache-prefix : "shiro-redis-cache"
    #shiro缓存在redis过期时间是(分钟)
    cache-time : 180
# jwt 配置
jwt:
  # 加密密钥
  secret: 61D73234C4F93E03074D74D74D1E39D9 #blog.wuwii.com
  # token有效时长
  expire: 7 # 7天，单位天
  # token 存在 header 中的参数
  header: token

#公共配置
#项目信息
info: 
  app.name: random-service
  company.name: jiurun
  build.artifactId: $project.artifactId$
  build.version: $project.version$